### ISSUE TITLE
Sign multiple search patterns

### ISSUE THREAD

**Issue by mregni** [StefanKert/azuredevops-codesigning-task#16]
Love this task, thanks for your time!

Just one question. Is it possible to make the "File(s) to sign" field multiline? So we can have a config like this:
```
  - task: codesigning@2
    displayName: 'Signing output files'
    inputs:
      secureFileId: 'mycert.pfx'
      signCertPassword: '$(PfxPassword)'
      files: |
        **/MyOwn.*.dll
        **/Other.*.dll
        **/*.exe
      timeServer: 'http://timestamp.digicert.com'
      hashingAlgorithm: 'SHA256'
```

Now I need 3 steps instead of one (if multiline was supported). If needed, I can take some time and create a PR for that.

**Comment by StefanKert** [comment]
Hi @mregni,

although multiline is not yet supported you can use a single task with a RegEx expression

```
  - task: codesigning@2
    displayName: 'Signing output files'
    inputs:
      secureFileId: 'mycert.pfx'
      signCertPassword: '$(PfxPassword)'
      files: '**/+(MyOwn.*.dll|Other.*.dll|*.exe)'
      timeServer: 'http://timestamp.digicert.com'
      hashingAlgorithm: 'SHA256'
```
So I guess this could solve the issue of having to create three tasks right now, but I totally agree that multiline support would be easier to use. I´d greatly appreciate a PR because I am currently a bit busy with other projects, so if you have the time it would be amazing.
