### ISSUE TITLE
Should Code Signing be used in the build pipeline or release pipeline?

### ISSUE THREAD

**Issue by Rod-in-NM** [StefanKert/azuredevops-codesigning-task#35]
On the Visual Studio Marketplace, the description of Code Signing is this:

> Build task for Azure DevOps that gives the user the ability to codesign assemblies and applications

I'm working on setting up my first Azure DevOps Services Pipeline for building and releasing a WPF application. I really would have thought Code Signing should be used in the release pipeline for ADS, not the build pipeline. Am I wrong about that?

**Comment by Rod-in-NM** [comment]
FWIW, I'm using it in the Release Pipeline. It seems the correct place to use it, but I would love to know if I'm wrong.

**Comment by StefanKert** [comment]
Hi @Rod-in-NM,

afaik most Users are using it as part of their build pipeline to make sure that the artifacts that are created by the build are correctly singed. Generally, I would suggest to keep the code signing as close as possible to the actual build task to ensure the integrity of the built artifacts.

**Comment by jakubtrebacz-dev** [comment]
@StefanKert 
Any chance you could post the yaml example of how to use this extension? I can't see any examples out here

**Comment by jakubtrebacz-dev** [comment]
Never mind just found it
```yaml 
  - task: codesigning@2
    displayName: Code Signing Assemblies
    inputs:
      secureFileId: $(CodeSigningFileId)
      signCertPassword: '$(code-signing-password)'
      files: '**/bin/**/$(buildConfiguration)/**/@(*.exe|*.dll)'
      hashingAlgorithm: 'SHA256'
```
